package om.gov.rop.person;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.0
 * 2024-10-07T10:11:58.991+04:00
 * Generated source version: 3.6.0
 *
 */
@WebService(targetNamespace = "urn:rop-gov-om:person", name = "PersonInformation_WSSP_ASE_PortType")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonInformationWSSPASEPortType {

    @WebMethod(operationName = "PersonInformation", action = "PersonInformation_Entities_External_ws_PersonInformation_WSSP_ASE_Binder_PersonInformation")
    @RequestWrapper(localName = "PersonInformation", targetNamespace = "urn:rop-gov-om:person", className = "om.gov.rop.person.PersonInformation")
    @ResponseWrapper(localName = "PersonInformationResponse", targetNamespace = "urn:rop-gov-om:person", className = "om.gov.rop.person.PersonInformationResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public om.gov.rop.person.Response personInformation(

        @WebParam(name = "PersonRequest", targetNamespace = "")
        om.gov.rop.person.PersonRequest personRequest
    );
}
