package om.gov.rop.trafficinformation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.0
 * 2023-05-29T10:40:44.239+04:00
 * Generated source version: 3.6.0
 *
 */
@WebService(targetNamespace = "urn:rop-gov-om:TrafficInformation", name = "TrafficInformation_ASE_PortType")
@XmlSeeAlso({ObjectFactory.class})
public interface TrafficInformationASEPortType {

    @WebMethod(operationName = "TrafficInformation", action = "TrafficInformation_Entities_ws_provider_TrafficInformation_ASE_Binder_TrafficInformation")
    @RequestWrapper(localName = "TrafficInformation", targetNamespace = "urn:rop-gov-om:TrafficInformation", className = "om.gov.rop.trafficinformation.TrafficInformation")
    @ResponseWrapper(localName = "TrafficInformationResponse", targetNamespace = "urn:rop-gov-om:TrafficInformation", className = "om.gov.rop.trafficinformation.TrafficInformationResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public om.gov.rop.trafficinformation.TrafficInformationResponse2 trafficInformation(

        @WebParam(name = "Request", targetNamespace = "")
        om.gov.rop.trafficinformation.TrafficInformationRequest request
    );
}
