package com.oracle.ouaf.webservices.cm.cmaddpayevt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.4.2
 * 2023-05-22T11:15:37.446+04:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "CMAddPayEvtSoapBindingQSService",
                  wsdlLocation = "file:/D:/Vinsys-owwsc/PAW-diamservice/diamservices/src/main/resources/wsdl/CMWaterAddPayEvtProxyService_PAEW.wsdl",
                  targetNamespace = "http://ouaf.oracle.com/webservices/cm/CMAddPayEvt")
public class CMAddPayEvtSoapBindingQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ouaf.oracle.com/webservices/cm/CMAddPayEvt", "CMAddPayEvtSoapBindingQSService");
    public final static QName CMAddPayEvtSoapBindingQSPort = new QName("http://ouaf.oracle.com/webservices/cm/CMAddPayEvt", "CMAddPayEvtSoapBindingQSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Vinsys-owwsc/PAW-diamservice/diamservices/src/main/resources/wsdl/CMWaterAddPayEvtProxyService_PAEW.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CMAddPayEvtSoapBindingQSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Vinsys-owwsc/PAW-diamservice/diamservices/src/main/resources/wsdl/CMWaterAddPayEvtProxyService_PAEW.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CMAddPayEvtSoapBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CMAddPayEvtSoapBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMAddPayEvtSoapBindingQSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CMAddPayEvtSoapBindingQSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CMAddPayEvtSoapBindingQSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CMAddPayEvtSoapBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CMAddPayEvtPortType
     */
    @WebEndpoint(name = "CMAddPayEvtSoapBindingQSPort")
    public CMAddPayEvtPortType getCMAddPayEvtSoapBindingQSPort() {
        return super.getPort(CMAddPayEvtSoapBindingQSPort, CMAddPayEvtPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMAddPayEvtPortType
     */
    @WebEndpoint(name = "CMAddPayEvtSoapBindingQSPort")
    public CMAddPayEvtPortType getCMAddPayEvtSoapBindingQSPort(WebServiceFeature... features) {
        return super.getPort(CMAddPayEvtSoapBindingQSPort, CMAddPayEvtPortType.class, features);
    }

}
