package com.oracle.ouaf.webservices.cm.cmaddpayevt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2023-05-22T11:15:37.431+04:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://ouaf.oracle.com/webservices/cm/CMAddPayEvt", name = "CMAddPayEvtPortType")
@XmlSeeAlso({ObjectFactory.class, com.oracle.ouaf.ObjectFactory.class})
public interface CMAddPayEvtPortType {

    @WebMethod(operationName = "CMAddPayEvt", action = "http://localhost/webservices/CMAddPayEvt#CMAddPayEvt")
    @RequestWrapper(localName = "CMAddPayEvt", targetNamespace = "http://ouaf.oracle.com/webservices/cm/CMAddPayEvt", className = "com.oracle.ouaf.webservices.cm.cmaddpayevt.CMAddPayEvt")
    @ResponseWrapper(localName = "CMAddPayEvt", targetNamespace = "http://ouaf.oracle.com/webservices/cm/CMAddPayEvt", className = "com.oracle.ouaf.webservices.cm.cmaddpayevt.CMAddPayEvt")
    public void cmAddPayEvt(

        @WebParam(mode = WebParam.Mode.INOUT, name = "input", targetNamespace = "http://ouaf.oracle.com/webservices/cm/CMAddPayEvt")
        javax.xml.ws.Holder<com.oracle.ouaf.webservices.cm.cmaddpayevt.CMAddPayEvt.Input> input,
        @WebParam(mode = WebParam.Mode.INOUT, name = "output", targetNamespace = "http://ouaf.oracle.com/webservices/cm/CMAddPayEvt")
        javax.xml.ws.Holder<com.oracle.ouaf.webservices.cm.cmaddpayevt.CMAddPayEvt.Output> output
    ) throws Fault;
}
