
package com.oracle.ouaf.webservices.cm.cmaddpayevt;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.2
 * 2023-05-22T11:15:37.402+04:00
 * Generated source version: 3.4.2
 */

@WebFault(name = "Fault", targetNamespace = "http://ouaf.oracle.com/")
public class Fault extends Exception {

    private com.oracle.ouaf.Fault faultInfo;

    public Fault() {
        super();
    }

    public Fault(String message) {
        super(message);
    }

    public Fault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Fault(String message, com.oracle.ouaf.Fault fault) {
        super(message);
        this.faultInfo = fault;
    }

    public Fault(String message, com.oracle.ouaf.Fault fault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fault;
    }

    public com.oracle.ouaf.Fault getFaultInfo() {
        return this.faultInfo;
    }
}
